#!/usr/bin/env bash
# Vendor the canonical tables and crate version into this package before
# packing. The repository keeps no duplicates: `tables/` and `Cargo.toml`
# at the cdate root stay canonical; `src/generated/` is regenerated.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"

mkdir -p "$HERE/src/generated" "$ROOT/typst/generated" "$ROOT/py/cdate"

VERSION="$(grep -m1 '^version' "$ROOT/Cargo.toml" | sed 's/.*"\(.*\)"/\1/')"

python3 - "$HERE" "$ROOT" "$VERSION" <<'EOF'
import json
import sys

here, root, version = sys.argv[1], sys.argv[2], sys.argv[3]
with open(f"{root}/tables/dates.json", encoding="utf-8") as handle:
    dates = json.load(handle)
out = (
    "// GENERATED by scripts/sync-assets.sh — do not edit.\n"
    f"export const PACKAGE_VERSION: string = {json.dumps(version)};\n"
    f"export const DATES_TABLE: unknown = {json.dumps(dates, ensure_ascii=False)};\n"
)
with open(f"{here}/src/generated/tables.ts", "w", encoding="utf-8") as handle:
    handle.write(out)


def typst_str(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def typst_array(values, col):
    single = "(" + ", ".join(typst_str(item) for item in values) + ")"
    if col + len(single) <= 120:
        return single
    return "(\n" + "".join(f"        {typst_str(item)},\n" for item in values) + "      )"


def typst_entry(key, entry):
    fields = [
        f"long: {typst_str(entry['long'])}",
        f"medium: {typst_str(entry['medium'])}",
        f"short: {typst_str(entry['short'])}",
        f"month_year: {typst_str(entry['month_year'])}",
        # Array fields start at visual column 20 (6 spaces + field name);
        # broken items indent to nesting depth (8), closing paren to 6.
        f"months_long: {typst_array(entry['months_long'], 20)}",
    ]
    if "months_short" in entry:
        fields.append(
            f"months_short: {typst_array(entry['months_short'], 21)}"
        )
    body = ",\n      ".join(fields)
    return f"{typst_str(key)}: (\n      {body},\n    )"


entries = ",\n    ".join(
    typst_entry(key, entry) for key, entry in dates["locales"].items()
)
typ = (
    "// GENERATED by js/@corbet-labs/cdate/scripts/sync-assets.sh — do not edit.\n"
    "#let dates-table = (\n"
    f"  locales: (\n    {entries},\n  ),\n"
    f"  supported: {typst_array(dates['supported'], 2)},\n"
    f"  fallback: {typst_str(dates['fallback'])},\n"
    ")\n"
)
with open(f"{root}/typst/generated/dates.typ", "w", encoding="utf-8") as handle:
    handle.write(typ)
print(f"synced tables/dates.json, version {version}")
EOF

python3 "$ROOT/scripts/sync-python.py"
