schema = 1

[github]
repository = "corbet-foss/cdate"
workflow = "ccid.yml"
workflow_sha256 = "a9da3067d150ce8108ac80c256fd0eaec30f6f99ce6624d48b23d8e51c75973e"
checks = ["rust"]
platform = "linux-x86_64"
secret_free = true
free_eligible = true
tool_revision = "27c248aefa3c7198be6716a884d290c717774b21"
tool_bootstrap_workflow = "bootstrap.yml"
tool_bootstrap_sha256 = "d275261db8126e8d579184024a9eb4eaeedb15fcb7801804697d396c48e391ae"

[dependencies]
files = ["Cargo.lock", "Cargo.toml"]
